/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'caseDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAllInquiries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Inquiry))],
      ['query'],
    ),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'caseDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAllInquiries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Inquiry))],
        ['query'],
      ),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };